name: Prettier check
on:
  workflow_dispatch:
  pull_request:
jobs:
  prettier-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install prettier
        run: |
          npm i -g prettier
      - name: Check formatting with prettier
        run: |
          prettier -c .
